### ISSUE TITLE
[ADD] 소음 분류 매뉴얼 뷰 구현하기

### ISSUE THREAD

**Issue by KimDaeSeong8721** [4NTJ/Quiet#11]
## 💡 Issue

- 소음 분류 매뉴얼 뷰를 구현합니다.
## 📝  todo

- [x] Noise라는 모델 생성하기
- [x] noiseInfoView라는 커스텀뷰 제작하기
- [x] 소음 분류 매뉴얼 버튼과 연결하기
- [x] URL연결하기
