### ISSUE TITLE
[ADD] 상세 소음정보 화면 UI 구현

### ISSUE THREAD

**Issue by Minkyeong-Ko** [4NTJ/Quiet#15]
## 💡 Issue
상세 소음정보 화면을 구현합니다

## 📝  todo

- [ ] Navigation Bar에 뒤로 가기 버튼, 동 이름 추가
- [ ] 소음 정보 멘트와 데시벨 정보 부분
- [ ] 시간별 소음 변화 차트
- [ ] 평일/주말 소음 비교 차트
