### ISSUE TITLE
[ADD] Charts 라이브러리 추가 및 테스트 차트 만들기

### ISSUE THREAD

**Issue by Minkyeong-Ko** [4NTJ/Quiet#4]
## 💡 Issue
Charts 라이브러리를 추가하고 테스트 차트를 만듭니다.

## 📝  todo

- [x] SPM 사용해 Charts 라이브러리 추가
- [x] LineChart 만들기 (시간별 소음)
- [x] BarChart 만들기 (주말/주중 비교)
