### ISSUE TITLE
[FEAT] 마커를 누르면 하단에 내용이 뜨도록 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [4NTJ/Quiet#52]
## 💡 Issue

마커를 눌렀을 시에 하단에 내용이 뜨도록 구현합니다.

## 📝  todo

- [x] select에서 하단 데이터 설정하도록 구현
- [x] 눌렀을 때 현재 상태를 색상으로(원) 할 수 있는 지 확인
- [x] 넘어오는 데이터가 없을 시 구현
