### ISSUE TITLE
[FEAT] 맵뷰에 측정장치위치 표시하기

### ISSUE THREAD

**Issue by KimDaeSeong8721** [4NTJ/Quiet#57]
## 💡 Issue

- 맵뷰에 측정장치의 위치 표시하기
<img width="379" alt="image" src="https://user-images.githubusercontent.com/69894461/186940364-87aff866-0e8a-498f-b0ca-864e1788053b.png">

- 측정장치의 위치 어노테이션버튼 클릭시 정보 표시
- 팝업창 클릭시 디테일뷰로 옮기기
## 📝  todo

- [ ] API로 데이터 받아오기
- [ ] 어노테이션 뷰 만들기
- [ ] 어노테이션 뷰 맵뷰에 표시하기
- [ ] 어노테이션 뷰 클릭시 정보 표시하기
- [ ] 팝업창 클릭시 디테일뷰로 옮기기
