### ISSUE TITLE
[ADD] 검색을 했을 시에 검색 결과가 쌓이는 로직 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [4NTJ/Quiet#6]
## 💡 Issue

검색을 했을 시에 검색 결과가 쌓이는 로직 구현합니다.

## 📝  todo

- [x] 검색 결과 쌓는 로직 구현
- [x] 검색 결과 삭제 로직 구현
- [x] 전체 삭제 로직 구현
- [x] keyboard 올라왔을 시에 테이블 뷰 높이 짧아지도록 구현
