### ISSUE TITLE
[FIX] 상세 소음정보 화면 수정

### ISSUE THREAD

**Issue by Minkyeong-Ko** [4NTJ/Quiet#60]
## 💡 Issue

상세 소음정보 화면 UI를 수정합니다

## 📝  todo

- [x] 차트 높이 수정
- [x] 터치 시 색깔 변경 금지
- [ ] 차트 설명 추가
