### ISSUE TITLE
[FEAT] 상세 뷰에게 데이터 전달 구현

### ISSUE THREAD

**Issue by YoonAh-dev** [4NTJ/Quiet#65]
## 💡 Issue

상세 뷰에게 데이터 전달을 구현합니다.

## 📝  todo

- [x] 상단 title 전달
- [x] 하단 내용 전달
- [x] Device model 기기값 전달
